done 2nd js hm
js-tasks-ru/js-20220209_vitaliy385 pull request #2
Opened 2022-02-15 18:46 UTC by LosSantosWhite

2022-02-15 18:47 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-15 22:19 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  if (param === 'asc') {
В данном решении явные дубликаты кода - функции сортировки.
От дубликатов кода необходимо избавиться

2022-02-15 22:19 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let new_arr = [...arr];
проверьте, может тут `const`?

2022-02-15 22:20 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let new_arr = [...arr];
переменные в JS именуются в `camelCase`

2022-02-15 22:20 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (obj.hasOwnProperty(fields[i])) {
👍 лайк за использование `hasOwnProperty`

проверьте а тут точно переменные `let`?

2022-02-15 22:21 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +      delete new_obj[fields[i]];
использовать `delete` в связке с объектом не рекомендуется, ведь копирование объекта `{...obj}` или `Object.assign` делает `shallow copy` или другими словами неглубокую копию, поэтому удаление может привести к весьма неожиданным последствиям

2022-02-15 22:21 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let new_obj = {};
проверьте тут точно `let`?

2022-02-15 22:21 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-02-17 18:18 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-18 14:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-02-19 10:41 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const getter = (obj, arr=path.split('.')) => {
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-02-19 10:42 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return undefined;
просто `return`

2022-02-19 10:43 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  } else {
если в блоке `if` был `return`, то оставшуюся часть логики нет необходимости оборачивать в `else`

2022-02-19 10:43 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
`return` без `undefined`

2022-02-19 10:43 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
good 👍

2022-02-19 10:44 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return newArr
`Set` - это итерабельная структура, поэтому мы можем сделать вот так:
```
return [...new Set(arr)]
```

2022-02-19 10:44 UTC, dosandk approved these changes
решения принимаются, посмотрите пожалуйста комментарии :mag:

2022-02-19 10:45 UTC, merged